//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-rc.1
// 	protoc        v3.17.3
// source: HBase.proto

// This file contains protocol buffers that are shared throughout HBase

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Comparison operators
type CompareType int32

const (
	CompareType_LESS             CompareType = 0
	CompareType_LESS_OR_EQUAL    CompareType = 1
	CompareType_EQUAL            CompareType = 2
	CompareType_NOT_EQUAL        CompareType = 3
	CompareType_GREATER_OR_EQUAL CompareType = 4
	CompareType_GREATER          CompareType = 5
	CompareType_NO_OP            CompareType = 6
)

// Enum value maps for CompareType.
var (
	CompareType_name = map[int32]string{
		0: "LESS",
		1: "LESS_OR_EQUAL",
		2: "EQUAL",
		3: "NOT_EQUAL",
		4: "GREATER_OR_EQUAL",
		5: "GREATER",
		6: "NO_OP",
	}
	CompareType_value = map[string]int32{
		"LESS":             0,
		"LESS_OR_EQUAL":    1,
		"EQUAL":            2,
		"NOT_EQUAL":        3,
		"GREATER_OR_EQUAL": 4,
		"GREATER":          5,
		"NO_OP":            6,
	}
)

func (x CompareType) Enum() *CompareType {
	p := new(CompareType)
	*p = x
	return p
}

func (x CompareType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompareType) Descriptor() protoreflect.EnumDescriptor {
	return file_HBase_proto_enumTypes[0].Descriptor()
}

func (CompareType) Type() protoreflect.EnumType {
	return &file_HBase_proto_enumTypes[0]
}

func (x CompareType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CompareType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CompareType(num)
	return nil
}

// Deprecated: Use CompareType.Descriptor instead.
func (CompareType) EnumDescriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{0}
}

type TimeUnit int32

const (
	TimeUnit_NANOSECONDS  TimeUnit = 1
	TimeUnit_MICROSECONDS TimeUnit = 2
	TimeUnit_MILLISECONDS TimeUnit = 3
	TimeUnit_SECONDS      TimeUnit = 4
	TimeUnit_MINUTES      TimeUnit = 5
	TimeUnit_HOURS        TimeUnit = 6
	TimeUnit_DAYS         TimeUnit = 7
)

// Enum value maps for TimeUnit.
var (
	TimeUnit_name = map[int32]string{
		1: "NANOSECONDS",
		2: "MICROSECONDS",
		3: "MILLISECONDS",
		4: "SECONDS",
		5: "MINUTES",
		6: "HOURS",
		7: "DAYS",
	}
	TimeUnit_value = map[string]int32{
		"NANOSECONDS":  1,
		"MICROSECONDS": 2,
		"MILLISECONDS": 3,
		"SECONDS":      4,
		"MINUTES":      5,
		"HOURS":        6,
		"DAYS":         7,
	}
)

func (x TimeUnit) Enum() *TimeUnit {
	p := new(TimeUnit)
	*p = x
	return p
}

func (x TimeUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_HBase_proto_enumTypes[1].Descriptor()
}

func (TimeUnit) Type() protoreflect.EnumType {
	return &file_HBase_proto_enumTypes[1]
}

func (x TimeUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TimeUnit) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TimeUnit(num)
	return nil
}

// Deprecated: Use TimeUnit.Descriptor instead.
func (TimeUnit) EnumDescriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{1}
}

// Table's current state
type TableState_State int32

const (
	TableState_ENABLED   TableState_State = 0
	TableState_DISABLED  TableState_State = 1
	TableState_DISABLING TableState_State = 2
	TableState_ENABLING  TableState_State = 3
)

// Enum value maps for TableState_State.
var (
	TableState_State_name = map[int32]string{
		0: "ENABLED",
		1: "DISABLED",
		2: "DISABLING",
		3: "ENABLING",
	}
	TableState_State_value = map[string]int32{
		"ENABLED":   0,
		"DISABLED":  1,
		"DISABLING": 2,
		"ENABLING":  3,
	}
)

func (x TableState_State) Enum() *TableState_State {
	p := new(TableState_State)
	*p = x
	return p
}

func (x TableState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_HBase_proto_enumTypes[2].Descriptor()
}

func (TableState_State) Type() protoreflect.EnumType {
	return &file_HBase_proto_enumTypes[2]
}

func (x TableState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TableState_State) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TableState_State(num)
	return nil
}

// Deprecated: Use TableState_State.Descriptor instead.
func (TableState_State) EnumDescriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{2, 0}
}

type RegionSpecifier_RegionSpecifierType int32

const (
	// <tablename>,<startkey>,<regionId>.<encodedName>
	RegionSpecifier_REGION_NAME RegionSpecifier_RegionSpecifierType = 1
	// hash of <tablename>,<startkey>,<regionId>
	RegionSpecifier_ENCODED_REGION_NAME RegionSpecifier_RegionSpecifierType = 2
)

// Enum value maps for RegionSpecifier_RegionSpecifierType.
var (
	RegionSpecifier_RegionSpecifierType_name = map[int32]string{
		1: "REGION_NAME",
		2: "ENCODED_REGION_NAME",
	}
	RegionSpecifier_RegionSpecifierType_value = map[string]int32{
		"REGION_NAME":         1,
		"ENCODED_REGION_NAME": 2,
	}
)

func (x RegionSpecifier_RegionSpecifierType) Enum() *RegionSpecifier_RegionSpecifierType {
	p := new(RegionSpecifier_RegionSpecifierType)
	*p = x
	return p
}

func (x RegionSpecifier_RegionSpecifierType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegionSpecifier_RegionSpecifierType) Descriptor() protoreflect.EnumDescriptor {
	return file_HBase_proto_enumTypes[3].Descriptor()
}

func (RegionSpecifier_RegionSpecifierType) Type() protoreflect.EnumType {
	return &file_HBase_proto_enumTypes[3]
}

func (x RegionSpecifier_RegionSpecifierType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RegionSpecifier_RegionSpecifierType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RegionSpecifier_RegionSpecifierType(num)
	return nil
}

// Deprecated: Use RegionSpecifier_RegionSpecifierType.Descriptor instead.
func (RegionSpecifier_RegionSpecifierType) EnumDescriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{6, 0}
}

//*
// Table Name
type TableName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace []byte `protobuf:"bytes,1,req,name=namespace" json:"namespace,omitempty"`
	Qualifier []byte `protobuf:"bytes,2,req,name=qualifier" json:"qualifier,omitempty"`
}

func (x *TableName) Reset() {
	*x = TableName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableName) ProtoMessage() {}

func (x *TableName) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableName.ProtoReflect.Descriptor instead.
func (*TableName) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{0}
}

func (x *TableName) GetNamespace() []byte {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *TableName) GetQualifier() []byte {
	if x != nil {
		return x.Qualifier
	}
	return nil
}

//*
// Table Schema
// Inspired by the rest TableSchema
type TableSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName      *TableName            `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Attributes     []*BytesBytesPair     `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty"`
	ColumnFamilies []*ColumnFamilySchema `protobuf:"bytes,3,rep,name=column_families,json=columnFamilies" json:"column_families,omitempty"`
	Configuration  []*NameStringPair     `protobuf:"bytes,4,rep,name=configuration" json:"configuration,omitempty"`
}

func (x *TableSchema) Reset() {
	*x = TableSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSchema) ProtoMessage() {}

func (x *TableSchema) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSchema.ProtoReflect.Descriptor instead.
func (*TableSchema) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{1}
}

func (x *TableSchema) GetTableName() *TableName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *TableSchema) GetAttributes() []*BytesBytesPair {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *TableSchema) GetColumnFamilies() []*ColumnFamilySchema {
	if x != nil {
		return x.ColumnFamilies
	}
	return nil
}

func (x *TableSchema) GetConfiguration() []*NameStringPair {
	if x != nil {
		return x.Configuration
	}
	return nil
}

//* Denotes state of the table
type TableState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This is the table's state.
	State *TableState_State `protobuf:"varint,1,req,name=state,enum=hbase.pb.TableState_State" json:"state,omitempty"`
}

func (x *TableState) Reset() {
	*x = TableState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableState) ProtoMessage() {}

func (x *TableState) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableState.ProtoReflect.Descriptor instead.
func (*TableState) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{2}
}

func (x *TableState) GetState() TableState_State {
	if x != nil && x.State != nil {
		return *x.State
	}
	return TableState_ENABLED
}

//*
// Column Family Schema
// Inspired by the rest ColumSchemaMessage
type ColumnFamilySchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          []byte            `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Attributes    []*BytesBytesPair `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty"`
	Configuration []*NameStringPair `protobuf:"bytes,3,rep,name=configuration" json:"configuration,omitempty"`
}

func (x *ColumnFamilySchema) Reset() {
	*x = ColumnFamilySchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnFamilySchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnFamilySchema) ProtoMessage() {}

func (x *ColumnFamilySchema) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnFamilySchema.ProtoReflect.Descriptor instead.
func (*ColumnFamilySchema) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{3}
}

func (x *ColumnFamilySchema) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *ColumnFamilySchema) GetAttributes() []*BytesBytesPair {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ColumnFamilySchema) GetConfiguration() []*NameStringPair {
	if x != nil {
		return x.Configuration
	}
	return nil
}

//*
// Protocol buffer version of HRegionInfo.
type RegionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionId  *uint64    `protobuf:"varint,1,req,name=region_id,json=regionId" json:"region_id,omitempty"`
	TableName *TableName `protobuf:"bytes,2,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	StartKey  []byte     `protobuf:"bytes,3,opt,name=start_key,json=startKey" json:"start_key,omitempty"`
	EndKey    []byte     `protobuf:"bytes,4,opt,name=end_key,json=endKey" json:"end_key,omitempty"`
	Offline   *bool      `protobuf:"varint,5,opt,name=offline" json:"offline,omitempty"`
	Split     *bool      `protobuf:"varint,6,opt,name=split" json:"split,omitempty"`
	ReplicaId *int32     `protobuf:"varint,7,opt,name=replica_id,json=replicaId,def=0" json:"replica_id,omitempty"`
}

// Default values for RegionInfo fields.
const (
	Default_RegionInfo_ReplicaId = int32(0)
)

func (x *RegionInfo) Reset() {
	*x = RegionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionInfo) ProtoMessage() {}

func (x *RegionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionInfo.ProtoReflect.Descriptor instead.
func (*RegionInfo) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{4}
}

func (x *RegionInfo) GetRegionId() uint64 {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return 0
}

func (x *RegionInfo) GetTableName() *TableName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *RegionInfo) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *RegionInfo) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *RegionInfo) GetOffline() bool {
	if x != nil && x.Offline != nil {
		return *x.Offline
	}
	return false
}

func (x *RegionInfo) GetSplit() bool {
	if x != nil && x.Split != nil {
		return *x.Split
	}
	return false
}

func (x *RegionInfo) GetReplicaId() int32 {
	if x != nil && x.ReplicaId != nil {
		return *x.ReplicaId
	}
	return Default_RegionInfo_ReplicaId
}

//*
// Protocol buffer for favored nodes
type FavoredNodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FavoredNode []*ServerName `protobuf:"bytes,1,rep,name=favored_node,json=favoredNode" json:"favored_node,omitempty"`
}

func (x *FavoredNodes) Reset() {
	*x = FavoredNodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavoredNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoredNodes) ProtoMessage() {}

func (x *FavoredNodes) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoredNodes.ProtoReflect.Descriptor instead.
func (*FavoredNodes) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{5}
}

func (x *FavoredNodes) GetFavoredNode() []*ServerName {
	if x != nil {
		return x.FavoredNode
	}
	return nil
}

//*
// Container protocol buffer to specify a region.
// You can specify region by region name, or the hash
// of the region name, which is known as encoded
// region name.
type RegionSpecifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  *RegionSpecifier_RegionSpecifierType `protobuf:"varint,1,req,name=type,enum=hbase.pb.RegionSpecifier_RegionSpecifierType" json:"type,omitempty"`
	Value []byte                               `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
}

func (x *RegionSpecifier) Reset() {
	*x = RegionSpecifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionSpecifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionSpecifier) ProtoMessage() {}

func (x *RegionSpecifier) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionSpecifier.ProtoReflect.Descriptor instead.
func (*RegionSpecifier) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{6}
}

func (x *RegionSpecifier) GetType() RegionSpecifier_RegionSpecifierType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return RegionSpecifier_REGION_NAME
}

func (x *RegionSpecifier) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

//*
// A range of time. Both from and to are Java time
// stamp in milliseconds. If you don't specify a time
// range, it means all time.  By default, if not
// specified, from = 0, and to = Long.MAX_VALUE
type TimeRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *uint64 `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To   *uint64 `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{7}
}

func (x *TimeRange) GetFrom() uint64 {
	if x != nil && x.From != nil {
		return *x.From
	}
	return 0
}

func (x *TimeRange) GetTo() uint64 {
	if x != nil && x.To != nil {
		return *x.To
	}
	return 0
}

type TimeRangeTracker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *uint64 `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To   *uint64 `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
}

func (x *TimeRangeTracker) Reset() {
	*x = TimeRangeTracker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeRangeTracker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRangeTracker) ProtoMessage() {}

func (x *TimeRangeTracker) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRangeTracker.ProtoReflect.Descriptor instead.
func (*TimeRangeTracker) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{8}
}

func (x *TimeRangeTracker) GetFrom() uint64 {
	if x != nil && x.From != nil {
		return *x.From
	}
	return 0
}

func (x *TimeRangeTracker) GetTo() uint64 {
	if x != nil && x.To != nil {
		return *x.To
	}
	return 0
}

// ColumnFamily Specific TimeRange
type ColumnFamilyTimeRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColumnFamily []byte     `protobuf:"bytes,1,req,name=column_family,json=columnFamily" json:"column_family,omitempty"`
	TimeRange    *TimeRange `protobuf:"bytes,2,req,name=time_range,json=timeRange" json:"time_range,omitempty"`
}

func (x *ColumnFamilyTimeRange) Reset() {
	*x = ColumnFamilyTimeRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnFamilyTimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnFamilyTimeRange) ProtoMessage() {}

func (x *ColumnFamilyTimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnFamilyTimeRange.ProtoReflect.Descriptor instead.
func (*ColumnFamilyTimeRange) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{9}
}

func (x *ColumnFamilyTimeRange) GetColumnFamily() []byte {
	if x != nil {
		return x.ColumnFamily
	}
	return nil
}

func (x *ColumnFamilyTimeRange) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

//*
// Protocol buffer version of ServerName
type ServerName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostName  *string `protobuf:"bytes,1,req,name=host_name,json=hostName" json:"host_name,omitempty"`
	Port      *uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	StartCode *uint64 `protobuf:"varint,3,opt,name=start_code,json=startCode" json:"start_code,omitempty"`
}

func (x *ServerName) Reset() {
	*x = ServerName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerName) ProtoMessage() {}

func (x *ServerName) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerName.ProtoReflect.Descriptor instead.
func (*ServerName) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{10}
}

func (x *ServerName) GetHostName() string {
	if x != nil && x.HostName != nil {
		return *x.HostName
	}
	return ""
}

func (x *ServerName) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *ServerName) GetStartCode() uint64 {
	if x != nil && x.StartCode != nil {
		return *x.StartCode
	}
	return 0
}

type Coprocessor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
}

func (x *Coprocessor) Reset() {
	*x = Coprocessor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coprocessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coprocessor) ProtoMessage() {}

func (x *Coprocessor) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coprocessor.ProtoReflect.Descriptor instead.
func (*Coprocessor) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{11}
}

func (x *Coprocessor) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type NameStringPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
}

func (x *NameStringPair) Reset() {
	*x = NameStringPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameStringPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameStringPair) ProtoMessage() {}

func (x *NameStringPair) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameStringPair.ProtoReflect.Descriptor instead.
func (*NameStringPair) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{12}
}

func (x *NameStringPair) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *NameStringPair) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type NameBytesPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value []byte  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (x *NameBytesPair) Reset() {
	*x = NameBytesPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameBytesPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameBytesPair) ProtoMessage() {}

func (x *NameBytesPair) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameBytesPair.ProtoReflect.Descriptor instead.
func (*NameBytesPair) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{13}
}

func (x *NameBytesPair) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *NameBytesPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type BytesBytesPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  []byte `protobuf:"bytes,1,req,name=first" json:"first,omitempty"`
	Second []byte `protobuf:"bytes,2,req,name=second" json:"second,omitempty"`
}

func (x *BytesBytesPair) Reset() {
	*x = BytesBytesPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesBytesPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesBytesPair) ProtoMessage() {}

func (x *BytesBytesPair) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesBytesPair.ProtoReflect.Descriptor instead.
func (*BytesBytesPair) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{14}
}

func (x *BytesBytesPair) GetFirst() []byte {
	if x != nil {
		return x.First
	}
	return nil
}

func (x *BytesBytesPair) GetSecond() []byte {
	if x != nil {
		return x.Second
	}
	return nil
}

type NameInt64Pair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value *int64  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (x *NameInt64Pair) Reset() {
	*x = NameInt64Pair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameInt64Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameInt64Pair) ProtoMessage() {}

func (x *NameInt64Pair) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameInt64Pair.ProtoReflect.Descriptor instead.
func (*NameInt64Pair) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{15}
}

func (x *NameInt64Pair) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *NameInt64Pair) GetValue() int64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

//*
// Description of the distributed procedure to take
type ProcedureDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature     *string           `protobuf:"bytes,1,req,name=signature" json:"signature,omitempty"` // the unique signature of the procedure
	Instance      *string           `protobuf:"bytes,2,opt,name=instance" json:"instance,omitempty"`   // the procedure instance name
	CreationTime  *int64            `protobuf:"varint,3,opt,name=creation_time,json=creationTime,def=0" json:"creation_time,omitempty"`
	Configuration []*NameStringPair `protobuf:"bytes,4,rep,name=configuration" json:"configuration,omitempty"`
}

// Default values for ProcedureDescription fields.
const (
	Default_ProcedureDescription_CreationTime = int64(0)
)

func (x *ProcedureDescription) Reset() {
	*x = ProcedureDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcedureDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureDescription) ProtoMessage() {}

func (x *ProcedureDescription) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureDescription.ProtoReflect.Descriptor instead.
func (*ProcedureDescription) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{16}
}

func (x *ProcedureDescription) GetSignature() string {
	if x != nil && x.Signature != nil {
		return *x.Signature
	}
	return ""
}

func (x *ProcedureDescription) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

func (x *ProcedureDescription) GetCreationTime() int64 {
	if x != nil && x.CreationTime != nil {
		return *x.CreationTime
	}
	return Default_ProcedureDescription_CreationTime
}

func (x *ProcedureDescription) GetConfiguration() []*NameStringPair {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type EmptyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMsg) Reset() {
	*x = EmptyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMsg) ProtoMessage() {}

func (x *EmptyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMsg.ProtoReflect.Descriptor instead.
func (*EmptyMsg) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{17}
}

type LongMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongMsg *int64 `protobuf:"varint,1,req,name=long_msg,json=longMsg" json:"long_msg,omitempty"`
}

func (x *LongMsg) Reset() {
	*x = LongMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongMsg) ProtoMessage() {}

func (x *LongMsg) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongMsg.ProtoReflect.Descriptor instead.
func (*LongMsg) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{18}
}

func (x *LongMsg) GetLongMsg() int64 {
	if x != nil && x.LongMsg != nil {
		return *x.LongMsg
	}
	return 0
}

type DoubleMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoubleMsg *float64 `protobuf:"fixed64,1,req,name=double_msg,json=doubleMsg" json:"double_msg,omitempty"`
}

func (x *DoubleMsg) Reset() {
	*x = DoubleMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleMsg) ProtoMessage() {}

func (x *DoubleMsg) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleMsg.ProtoReflect.Descriptor instead.
func (*DoubleMsg) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{19}
}

func (x *DoubleMsg) GetDoubleMsg() float64 {
	if x != nil && x.DoubleMsg != nil {
		return *x.DoubleMsg
	}
	return 0
}

type BigDecimalMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BigdecimalMsg []byte `protobuf:"bytes,1,req,name=bigdecimal_msg,json=bigdecimalMsg" json:"bigdecimal_msg,omitempty"`
}

func (x *BigDecimalMsg) Reset() {
	*x = BigDecimalMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BigDecimalMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigDecimalMsg) ProtoMessage() {}

func (x *BigDecimalMsg) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigDecimalMsg.ProtoReflect.Descriptor instead.
func (*BigDecimalMsg) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{20}
}

func (x *BigDecimalMsg) GetBigdecimalMsg() []byte {
	if x != nil {
		return x.BigdecimalMsg
	}
	return nil
}

type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeastSigBits *uint64 `protobuf:"varint,1,req,name=least_sig_bits,json=leastSigBits" json:"least_sig_bits,omitempty"`
	MostSigBits  *uint64 `protobuf:"varint,2,req,name=most_sig_bits,json=mostSigBits" json:"most_sig_bits,omitempty"`
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{21}
}

func (x *UUID) GetLeastSigBits() uint64 {
	if x != nil && x.LeastSigBits != nil {
		return *x.LeastSigBits
	}
	return 0
}

func (x *UUID) GetMostSigBits() uint64 {
	if x != nil && x.MostSigBits != nil {
		return *x.MostSigBits
	}
	return 0
}

type NamespaceDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          []byte            `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Configuration []*NameStringPair `protobuf:"bytes,2,rep,name=configuration" json:"configuration,omitempty"`
}

func (x *NamespaceDescriptor) Reset() {
	*x = NamespaceDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespaceDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceDescriptor) ProtoMessage() {}

func (x *NamespaceDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceDescriptor.ProtoReflect.Descriptor instead.
func (*NamespaceDescriptor) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{22}
}

func (x *NamespaceDescriptor) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *NamespaceDescriptor) GetConfiguration() []*NameStringPair {
	if x != nil {
		return x.Configuration
	}
	return nil
}

// Rpc client version info proto. Included in ConnectionHeader on connection setup
type VersionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version      *string `protobuf:"bytes,1,req,name=version" json:"version,omitempty"`
	Url          *string `protobuf:"bytes,2,req,name=url" json:"url,omitempty"`
	Revision     *string `protobuf:"bytes,3,req,name=revision" json:"revision,omitempty"`
	User         *string `protobuf:"bytes,4,req,name=user" json:"user,omitempty"`
	Date         *string `protobuf:"bytes,5,req,name=date" json:"date,omitempty"`
	SrcChecksum  *string `protobuf:"bytes,6,req,name=src_checksum,json=srcChecksum" json:"src_checksum,omitempty"`
	VersionMajor *uint32 `protobuf:"varint,7,opt,name=version_major,json=versionMajor" json:"version_major,omitempty"`
	VersionMinor *uint32 `protobuf:"varint,8,opt,name=version_minor,json=versionMinor" json:"version_minor,omitempty"`
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{23}
}

func (x *VersionInfo) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *VersionInfo) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *VersionInfo) GetRevision() string {
	if x != nil && x.Revision != nil {
		return *x.Revision
	}
	return ""
}

func (x *VersionInfo) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *VersionInfo) GetDate() string {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return ""
}

func (x *VersionInfo) GetSrcChecksum() string {
	if x != nil && x.SrcChecksum != nil {
		return *x.SrcChecksum
	}
	return ""
}

func (x *VersionInfo) GetVersionMajor() uint32 {
	if x != nil && x.VersionMajor != nil {
		return *x.VersionMajor
	}
	return 0
}

func (x *VersionInfo) GetVersionMinor() uint32 {
	if x != nil && x.VersionMinor != nil {
		return *x.VersionMinor
	}
	return 0
}

//*
// Description of the region server info
type RegionServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InfoPort    *int32       `protobuf:"varint,1,opt,name=infoPort" json:"infoPort,omitempty"`
	VersionInfo *VersionInfo `protobuf:"bytes,2,opt,name=version_info,json=versionInfo" json:"version_info,omitempty"`
}

func (x *RegionServerInfo) Reset() {
	*x = RegionServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionServerInfo) ProtoMessage() {}

func (x *RegionServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionServerInfo.ProtoReflect.Descriptor instead.
func (*RegionServerInfo) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{24}
}

func (x *RegionServerInfo) GetInfoPort() int32 {
	if x != nil && x.InfoPort != nil {
		return *x.InfoPort
	}
	return 0
}

func (x *RegionServerInfo) GetVersionInfo() *VersionInfo {
	if x != nil {
		return x.VersionInfo
	}
	return nil
}

type RegionExceptionMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region    *RegionSpecifier `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	Exception *NameBytesPair   `protobuf:"bytes,2,req,name=exception" json:"exception,omitempty"`
}

func (x *RegionExceptionMessage) Reset() {
	*x = RegionExceptionMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionExceptionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionExceptionMessage) ProtoMessage() {}

func (x *RegionExceptionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionExceptionMessage.ProtoReflect.Descriptor instead.
func (*RegionExceptionMessage) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{25}
}

func (x *RegionExceptionMessage) GetRegion() *RegionSpecifier {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *RegionExceptionMessage) GetException() *NameBytesPair {
	if x != nil {
		return x.Exception
	}
	return nil
}

type CacheEvictionStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EvictedBlocks *int64                    `protobuf:"varint,1,opt,name=evicted_blocks,json=evictedBlocks" json:"evicted_blocks,omitempty"`
	BytesEvicted  *int64                    `protobuf:"varint,2,opt,name=bytes_evicted,json=bytesEvicted" json:"bytes_evicted,omitempty"`
	MaxCacheSize  *int64                    `protobuf:"varint,3,opt,name=max_cache_size,json=maxCacheSize" json:"max_cache_size,omitempty"`
	Exception     []*RegionExceptionMessage `protobuf:"bytes,4,rep,name=exception" json:"exception,omitempty"`
}

func (x *CacheEvictionStats) Reset() {
	*x = CacheEvictionStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheEvictionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEvictionStats) ProtoMessage() {}

func (x *CacheEvictionStats) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEvictionStats.ProtoReflect.Descriptor instead.
func (*CacheEvictionStats) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{26}
}

func (x *CacheEvictionStats) GetEvictedBlocks() int64 {
	if x != nil && x.EvictedBlocks != nil {
		return *x.EvictedBlocks
	}
	return 0
}

func (x *CacheEvictionStats) GetBytesEvicted() int64 {
	if x != nil && x.BytesEvicted != nil {
		return *x.BytesEvicted
	}
	return 0
}

func (x *CacheEvictionStats) GetMaxCacheSize() int64 {
	if x != nil && x.MaxCacheSize != nil {
		return *x.MaxCacheSize
	}
	return 0
}

func (x *CacheEvictionStats) GetException() []*RegionExceptionMessage {
	if x != nil {
		return x.Exception
	}
	return nil
}

type RegionLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionInfo *RegionInfo `protobuf:"bytes,1,req,name=region_info,json=regionInfo" json:"region_info,omitempty"`
	ServerName *ServerName `protobuf:"bytes,2,opt,name=server_name,json=serverName" json:"server_name,omitempty"`
	SeqNum     *int64      `protobuf:"varint,3,req,name=seq_num,json=seqNum" json:"seq_num,omitempty"`
}

func (x *RegionLocation) Reset() {
	*x = RegionLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HBase_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionLocation) ProtoMessage() {}

func (x *RegionLocation) ProtoReflect() protoreflect.Message {
	mi := &file_HBase_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionLocation.ProtoReflect.Descriptor instead.
func (*RegionLocation) Descriptor() ([]byte, []int) {
	return file_HBase_proto_rawDescGZIP(), []int{27}
}

func (x *RegionLocation) GetRegionInfo() *RegionInfo {
	if x != nil {
		return x.RegionInfo
	}
	return nil
}

func (x *RegionLocation) GetServerName() *ServerName {
	if x != nil {
		return x.ServerName
	}
	return nil
}

func (x *RegionLocation) GetSeqNum() int64 {
	if x != nil && x.SeqNum != nil {
		return *x.SeqNum
	}
	return 0
}

var File_HBase_proto protoreflect.FileDescriptor

var file_HBase_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x48, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x68,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x22, 0x47, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x09, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x22, 0x82, 0x02, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x12, 0x32, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x62, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x42, 0x79, 0x74, 0x65, 0x73, 0x50, 0x61,
	0x69, 0x72, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x45,
	0x0a, 0x0f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x69, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x0e, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x46, 0x61, 0x6d,
	0x69, 0x6c, 0x69, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7f, 0x0a, 0x0a, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x3f, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44,
	0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x49, 0x53,
	0x41, 0x42, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x4e, 0x41, 0x42,
	0x4c, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x22, 0xa2, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x38, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x42, 0x79, 0x74, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x0d, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0d, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xe5, 0x01, 0x0a, 0x0a,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x08, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x65, 0x6e, 0x64, 0x4b, 0x65,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x70, 0x6c, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x70, 0x6c, 0x69,
	0x74, 0x12, 0x20, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x69, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x3a, 0x01, 0x30, 0x52, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x0c, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x65, 0x64, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x0c, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x65, 0x64, 0x5f, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x0b, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0xab, 0x01, 0x0a,
	0x0f, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x12, 0x41, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x2d,
	0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3f, 0x0a, 0x13, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10,
	0x01, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x4e, 0x43, 0x4f, 0x44, 0x45, 0x44, 0x5f, 0x52, 0x45, 0x47,
	0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x02, 0x22, 0x2f, 0x0a, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x10, 0x54,
	0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x15, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x46, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x46, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x12, 0x32, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x5c, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0x21, 0x0a, 0x0b, 0x43, 0x6f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x0e, 0x4e, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x39, 0x0a, 0x0d, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x50,
	0x61, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3e, 0x0a,
	0x0e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x42, 0x79, 0x74, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x05,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x39, 0x0a,
	0x0d, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x50, 0x61, 0x69, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xb8, 0x01, 0x0a, 0x14, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x0d, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x3a, 0x01, 0x30, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x50, 0x61, 0x69, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x0a, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x22,
	0x24, 0x0a, 0x07, 0x4c, 0x6f, 0x6e, 0x67, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f,
	0x6e, 0x67, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x07, 0x6c, 0x6f,
	0x6e, 0x67, 0x4d, 0x73, 0x67, 0x22, 0x2a, 0x0a, 0x09, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4d,
	0x73, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x01, 0x52, 0x09, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4d, 0x73,
	0x67, 0x22, 0x36, 0x0a, 0x0d, 0x42, 0x69, 0x67, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x4d,
	0x73, 0x67, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x69, 0x67, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c,
	0x5f, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x0d, 0x62, 0x69, 0x67, 0x64,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x22, 0x50, 0x0a, 0x04, 0x55, 0x55, 0x49,
	0x44, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x65, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x5f, 0x62,
	0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x0c, 0x6c, 0x65, 0x61, 0x73, 0x74,
	0x53, 0x69, 0x67, 0x42, 0x69, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x6f, 0x73, 0x74, 0x5f,
	0x73, 0x69, 0x67, 0x5f, 0x62, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04, 0x52, 0x0b,
	0x6d, 0x6f, 0x73, 0x74, 0x53, 0x69, 0x67, 0x42, 0x69, 0x74, 0x73, 0x22, 0x69, 0x0a, 0x13, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xea, 0x01, 0x0a, 0x0b, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x72, 0x63, 0x5f, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x72,
	0x63, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x23,
	0x0a, 0x0d, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x69,
	0x6e, 0x6f, 0x72, 0x22, 0x68, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x66, 0x6f, 0x50,
	0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x66, 0x6f, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x38, 0x0a, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0b, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x82, 0x01,
	0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x09, 0x65,
	0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72, 0x52, 0x09, 0x65, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0xc6, 0x01, 0x0a, 0x12, 0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x76, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x76, 0x69,
	0x63, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x65, 0x76, 0x69, 0x63, 0x74, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x65, 0x76, 0x69, 0x63, 0x74, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x62, 0x79, 0x74, 0x65, 0x73, 0x45, 0x76,
	0x69, 0x63, 0x74, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d,
	0x61, 0x78, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x65,
	0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x09, 0x65, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x97, 0x01, 0x0a, 0x0e,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35,
	0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x65, 0x71, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x65, 0x71, 0x4e, 0x75, 0x6d, 0x2a, 0x72, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x11,
	0x0a, 0x0d, 0x4c, 0x45, 0x53, 0x53, 0x5f, 0x4f, 0x52, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x47,
	0x52, 0x45, 0x41, 0x54, 0x45, 0x52, 0x5f, 0x4f, 0x52, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x10,
	0x04, 0x12, 0x0b, 0x0a, 0x07, 0x47, 0x52, 0x45, 0x41, 0x54, 0x45, 0x52, 0x10, 0x05, 0x12, 0x09,
	0x0a, 0x05, 0x4e, 0x4f, 0x5f, 0x4f, 0x50, 0x10, 0x06, 0x2a, 0x6e, 0x0a, 0x08, 0x54, 0x69, 0x6d,
	0x65, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x41, 0x4e, 0x4f, 0x53, 0x45, 0x43,
	0x4f, 0x4e, 0x44, 0x53, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x49, 0x43, 0x52, 0x4f, 0x53,
	0x45, 0x43, 0x4f, 0x4e, 0x44, 0x53, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x49, 0x4c, 0x4c,
	0x49, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x53, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45,
	0x43, 0x4f, 0x4e, 0x44, 0x53, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x49, 0x4e, 0x55, 0x54,
	0x45, 0x53, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x4f, 0x55, 0x52, 0x53, 0x10, 0x06, 0x12,
	0x08, 0x0a, 0x04, 0x44, 0x41, 0x59, 0x53, 0x10, 0x07, 0x42, 0x4c, 0x0a, 0x31, 0x6f, 0x72, 0x67,
	0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x0b,
	0x48, 0x42, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x48, 0x01, 0x5a, 0x05, 0x2e,
	0x2e, 0x2f, 0x70, 0x62, 0xa0, 0x01, 0x01,
}

var (
	file_HBase_proto_rawDescOnce sync.Once
	file_HBase_proto_rawDescData = file_HBase_proto_rawDesc
)

func file_HBase_proto_rawDescGZIP() []byte {
	file_HBase_proto_rawDescOnce.Do(func() {
		file_HBase_proto_rawDescData = protoimpl.X.CompressGZIP(file_HBase_proto_rawDescData)
	})
	return file_HBase_proto_rawDescData
}

var file_HBase_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_HBase_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_HBase_proto_goTypes = []interface{}{
	(CompareType)(0),                         // 0: hbase.pb.CompareType
	(TimeUnit)(0),                            // 1: hbase.pb.TimeUnit
	(TableState_State)(0),                    // 2: hbase.pb.TableState.State
	(RegionSpecifier_RegionSpecifierType)(0), // 3: hbase.pb.RegionSpecifier.RegionSpecifierType
	(*TableName)(nil),                        // 4: hbase.pb.TableName
	(*TableSchema)(nil),                      // 5: hbase.pb.TableSchema
	(*TableState)(nil),                       // 6: hbase.pb.TableState
	(*ColumnFamilySchema)(nil),               // 7: hbase.pb.ColumnFamilySchema
	(*RegionInfo)(nil),                       // 8: hbase.pb.RegionInfo
	(*FavoredNodes)(nil),                     // 9: hbase.pb.FavoredNodes
	(*RegionSpecifier)(nil),                  // 10: hbase.pb.RegionSpecifier
	(*TimeRange)(nil),                        // 11: hbase.pb.TimeRange
	(*TimeRangeTracker)(nil),                 // 12: hbase.pb.TimeRangeTracker
	(*ColumnFamilyTimeRange)(nil),            // 13: hbase.pb.ColumnFamilyTimeRange
	(*ServerName)(nil),                       // 14: hbase.pb.ServerName
	(*Coprocessor)(nil),                      // 15: hbase.pb.Coprocessor
	(*NameStringPair)(nil),                   // 16: hbase.pb.NameStringPair
	(*NameBytesPair)(nil),                    // 17: hbase.pb.NameBytesPair
	(*BytesBytesPair)(nil),                   // 18: hbase.pb.BytesBytesPair
	(*NameInt64Pair)(nil),                    // 19: hbase.pb.NameInt64Pair
	(*ProcedureDescription)(nil),             // 20: hbase.pb.ProcedureDescription
	(*EmptyMsg)(nil),                         // 21: hbase.pb.EmptyMsg
	(*LongMsg)(nil),                          // 22: hbase.pb.LongMsg
	(*DoubleMsg)(nil),                        // 23: hbase.pb.DoubleMsg
	(*BigDecimalMsg)(nil),                    // 24: hbase.pb.BigDecimalMsg
	(*UUID)(nil),                             // 25: hbase.pb.UUID
	(*NamespaceDescriptor)(nil),              // 26: hbase.pb.NamespaceDescriptor
	(*VersionInfo)(nil),                      // 27: hbase.pb.VersionInfo
	(*RegionServerInfo)(nil),                 // 28: hbase.pb.RegionServerInfo
	(*RegionExceptionMessage)(nil),           // 29: hbase.pb.RegionExceptionMessage
	(*CacheEvictionStats)(nil),               // 30: hbase.pb.CacheEvictionStats
	(*RegionLocation)(nil),                   // 31: hbase.pb.RegionLocation
}
var file_HBase_proto_depIdxs = []int32{
	4,  // 0: hbase.pb.TableSchema.table_name:type_name -> hbase.pb.TableName
	18, // 1: hbase.pb.TableSchema.attributes:type_name -> hbase.pb.BytesBytesPair
	7,  // 2: hbase.pb.TableSchema.column_families:type_name -> hbase.pb.ColumnFamilySchema
	16, // 3: hbase.pb.TableSchema.configuration:type_name -> hbase.pb.NameStringPair
	2,  // 4: hbase.pb.TableState.state:type_name -> hbase.pb.TableState.State
	18, // 5: hbase.pb.ColumnFamilySchema.attributes:type_name -> hbase.pb.BytesBytesPair
	16, // 6: hbase.pb.ColumnFamilySchema.configuration:type_name -> hbase.pb.NameStringPair
	4,  // 7: hbase.pb.RegionInfo.table_name:type_name -> hbase.pb.TableName
	14, // 8: hbase.pb.FavoredNodes.favored_node:type_name -> hbase.pb.ServerName
	3,  // 9: hbase.pb.RegionSpecifier.type:type_name -> hbase.pb.RegionSpecifier.RegionSpecifierType
	11, // 10: hbase.pb.ColumnFamilyTimeRange.time_range:type_name -> hbase.pb.TimeRange
	16, // 11: hbase.pb.ProcedureDescription.configuration:type_name -> hbase.pb.NameStringPair
	16, // 12: hbase.pb.NamespaceDescriptor.configuration:type_name -> hbase.pb.NameStringPair
	27, // 13: hbase.pb.RegionServerInfo.version_info:type_name -> hbase.pb.VersionInfo
	10, // 14: hbase.pb.RegionExceptionMessage.region:type_name -> hbase.pb.RegionSpecifier
	17, // 15: hbase.pb.RegionExceptionMessage.exception:type_name -> hbase.pb.NameBytesPair
	29, // 16: hbase.pb.CacheEvictionStats.exception:type_name -> hbase.pb.RegionExceptionMessage
	8,  // 17: hbase.pb.RegionLocation.region_info:type_name -> hbase.pb.RegionInfo
	14, // 18: hbase.pb.RegionLocation.server_name:type_name -> hbase.pb.ServerName
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_HBase_proto_init() }
func file_HBase_proto_init() {
	if File_HBase_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_HBase_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnFamilySchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavoredNodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionSpecifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeRangeTracker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnFamilyTimeRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coprocessor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameStringPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameBytesPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BytesBytesPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameInt64Pair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcedureDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BigDecimalMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamespaceDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionExceptionMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheEvictionStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HBase_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_HBase_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HBase_proto_goTypes,
		DependencyIndexes: file_HBase_proto_depIdxs,
		EnumInfos:         file_HBase_proto_enumTypes,
		MessageInfos:      file_HBase_proto_msgTypes,
	}.Build()
	File_HBase_proto = out.File
	file_HBase_proto_rawDesc = nil
	file_HBase_proto_goTypes = nil
	file_HBase_proto_depIdxs = nil
}
