//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-rc.1
// 	protoc        v3.17.3
// source: Quota.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuotaScope int32

const (
	QuotaScope_CLUSTER QuotaScope = 1
	QuotaScope_MACHINE QuotaScope = 2
)

// Enum value maps for QuotaScope.
var (
	QuotaScope_name = map[int32]string{
		1: "CLUSTER",
		2: "MACHINE",
	}
	QuotaScope_value = map[string]int32{
		"CLUSTER": 1,
		"MACHINE": 2,
	}
)

func (x QuotaScope) Enum() *QuotaScope {
	p := new(QuotaScope)
	*p = x
	return p
}

func (x QuotaScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuotaScope) Descriptor() protoreflect.EnumDescriptor {
	return file_Quota_proto_enumTypes[0].Descriptor()
}

func (QuotaScope) Type() protoreflect.EnumType {
	return &file_Quota_proto_enumTypes[0]
}

func (x QuotaScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *QuotaScope) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = QuotaScope(num)
	return nil
}

// Deprecated: Use QuotaScope.Descriptor instead.
func (QuotaScope) EnumDescriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{0}
}

type ThrottleType int32

const (
	ThrottleType_REQUEST_NUMBER        ThrottleType = 1
	ThrottleType_REQUEST_SIZE          ThrottleType = 2
	ThrottleType_WRITE_NUMBER          ThrottleType = 3
	ThrottleType_WRITE_SIZE            ThrottleType = 4
	ThrottleType_READ_NUMBER           ThrottleType = 5
	ThrottleType_READ_SIZE             ThrottleType = 6
	ThrottleType_REQUEST_CAPACITY_UNIT ThrottleType = 7
	ThrottleType_WRITE_CAPACITY_UNIT   ThrottleType = 8
	ThrottleType_READ_CAPACITY_UNIT    ThrottleType = 9
)

// Enum value maps for ThrottleType.
var (
	ThrottleType_name = map[int32]string{
		1: "REQUEST_NUMBER",
		2: "REQUEST_SIZE",
		3: "WRITE_NUMBER",
		4: "WRITE_SIZE",
		5: "READ_NUMBER",
		6: "READ_SIZE",
		7: "REQUEST_CAPACITY_UNIT",
		8: "WRITE_CAPACITY_UNIT",
		9: "READ_CAPACITY_UNIT",
	}
	ThrottleType_value = map[string]int32{
		"REQUEST_NUMBER":        1,
		"REQUEST_SIZE":          2,
		"WRITE_NUMBER":          3,
		"WRITE_SIZE":            4,
		"READ_NUMBER":           5,
		"READ_SIZE":             6,
		"REQUEST_CAPACITY_UNIT": 7,
		"WRITE_CAPACITY_UNIT":   8,
		"READ_CAPACITY_UNIT":    9,
	}
)

func (x ThrottleType) Enum() *ThrottleType {
	p := new(ThrottleType)
	*p = x
	return p
}

func (x ThrottleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThrottleType) Descriptor() protoreflect.EnumDescriptor {
	return file_Quota_proto_enumTypes[1].Descriptor()
}

func (ThrottleType) Type() protoreflect.EnumType {
	return &file_Quota_proto_enumTypes[1]
}

func (x ThrottleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ThrottleType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ThrottleType(num)
	return nil
}

// Deprecated: Use ThrottleType.Descriptor instead.
func (ThrottleType) EnumDescriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{1}
}

type QuotaType int32

const (
	QuotaType_THROTTLE QuotaType = 1
	QuotaType_SPACE    QuotaType = 2
)

// Enum value maps for QuotaType.
var (
	QuotaType_name = map[int32]string{
		1: "THROTTLE",
		2: "SPACE",
	}
	QuotaType_value = map[string]int32{
		"THROTTLE": 1,
		"SPACE":    2,
	}
)

func (x QuotaType) Enum() *QuotaType {
	p := new(QuotaType)
	*p = x
	return p
}

func (x QuotaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuotaType) Descriptor() protoreflect.EnumDescriptor {
	return file_Quota_proto_enumTypes[2].Descriptor()
}

func (QuotaType) Type() protoreflect.EnumType {
	return &file_Quota_proto_enumTypes[2]
}

func (x QuotaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *QuotaType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = QuotaType(num)
	return nil
}

// Deprecated: Use QuotaType.Descriptor instead.
func (QuotaType) EnumDescriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{2}
}

// Defines what action should be taken when the SpaceQuota is violated
type SpaceViolationPolicy int32

const (
	SpaceViolationPolicy_DISABLE               SpaceViolationPolicy = 1 // Disable the table(s)
	SpaceViolationPolicy_NO_WRITES_COMPACTIONS SpaceViolationPolicy = 2 // No writes, bulk-loads, or compactions
	SpaceViolationPolicy_NO_WRITES             SpaceViolationPolicy = 3 // No writes or bulk-loads
	SpaceViolationPolicy_NO_INSERTS            SpaceViolationPolicy = 4 // No puts or bulk-loads, but deletes are allowed
)

// Enum value maps for SpaceViolationPolicy.
var (
	SpaceViolationPolicy_name = map[int32]string{
		1: "DISABLE",
		2: "NO_WRITES_COMPACTIONS",
		3: "NO_WRITES",
		4: "NO_INSERTS",
	}
	SpaceViolationPolicy_value = map[string]int32{
		"DISABLE":               1,
		"NO_WRITES_COMPACTIONS": 2,
		"NO_WRITES":             3,
		"NO_INSERTS":            4,
	}
)

func (x SpaceViolationPolicy) Enum() *SpaceViolationPolicy {
	p := new(SpaceViolationPolicy)
	*p = x
	return p
}

func (x SpaceViolationPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpaceViolationPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_Quota_proto_enumTypes[3].Descriptor()
}

func (SpaceViolationPolicy) Type() protoreflect.EnumType {
	return &file_Quota_proto_enumTypes[3]
}

func (x SpaceViolationPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SpaceViolationPolicy) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SpaceViolationPolicy(num)
	return nil
}

// Deprecated: Use SpaceViolationPolicy.Descriptor instead.
func (SpaceViolationPolicy) EnumDescriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{3}
}

type TimedQuota struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeUnit  *TimeUnit   `protobuf:"varint,1,req,name=time_unit,json=timeUnit,enum=hbase.pb.TimeUnit" json:"time_unit,omitempty"`
	SoftLimit *uint64     `protobuf:"varint,2,opt,name=soft_limit,json=softLimit" json:"soft_limit,omitempty"`
	Share     *float32    `protobuf:"fixed32,3,opt,name=share" json:"share,omitempty"`
	Scope     *QuotaScope `protobuf:"varint,4,opt,name=scope,enum=hbase.pb.QuotaScope,def=2" json:"scope,omitempty"`
}

// Default values for TimedQuota fields.
const (
	Default_TimedQuota_Scope = QuotaScope_MACHINE
)

func (x *TimedQuota) Reset() {
	*x = TimedQuota{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimedQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimedQuota) ProtoMessage() {}

func (x *TimedQuota) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimedQuota.ProtoReflect.Descriptor instead.
func (*TimedQuota) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{0}
}

func (x *TimedQuota) GetTimeUnit() TimeUnit {
	if x != nil && x.TimeUnit != nil {
		return *x.TimeUnit
	}
	return TimeUnit_NANOSECONDS
}

func (x *TimedQuota) GetSoftLimit() uint64 {
	if x != nil && x.SoftLimit != nil {
		return *x.SoftLimit
	}
	return 0
}

func (x *TimedQuota) GetShare() float32 {
	if x != nil && x.Share != nil {
		return *x.Share
	}
	return 0
}

func (x *TimedQuota) GetScope() QuotaScope {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return Default_TimedQuota_Scope
}

type Throttle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqNum            *TimedQuota `protobuf:"bytes,1,opt,name=req_num,json=reqNum" json:"req_num,omitempty"`
	ReqSize           *TimedQuota `protobuf:"bytes,2,opt,name=req_size,json=reqSize" json:"req_size,omitempty"`
	WriteNum          *TimedQuota `protobuf:"bytes,3,opt,name=write_num,json=writeNum" json:"write_num,omitempty"`
	WriteSize         *TimedQuota `protobuf:"bytes,4,opt,name=write_size,json=writeSize" json:"write_size,omitempty"`
	ReadNum           *TimedQuota `protobuf:"bytes,5,opt,name=read_num,json=readNum" json:"read_num,omitempty"`
	ReadSize          *TimedQuota `protobuf:"bytes,6,opt,name=read_size,json=readSize" json:"read_size,omitempty"`
	ReqCapacityUnit   *TimedQuota `protobuf:"bytes,7,opt,name=req_capacity_unit,json=reqCapacityUnit" json:"req_capacity_unit,omitempty"`
	WriteCapacityUnit *TimedQuota `protobuf:"bytes,8,opt,name=write_capacity_unit,json=writeCapacityUnit" json:"write_capacity_unit,omitempty"`
	ReadCapacityUnit  *TimedQuota `protobuf:"bytes,9,opt,name=read_capacity_unit,json=readCapacityUnit" json:"read_capacity_unit,omitempty"`
}

func (x *Throttle) Reset() {
	*x = Throttle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Throttle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Throttle) ProtoMessage() {}

func (x *Throttle) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Throttle.ProtoReflect.Descriptor instead.
func (*Throttle) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{1}
}

func (x *Throttle) GetReqNum() *TimedQuota {
	if x != nil {
		return x.ReqNum
	}
	return nil
}

func (x *Throttle) GetReqSize() *TimedQuota {
	if x != nil {
		return x.ReqSize
	}
	return nil
}

func (x *Throttle) GetWriteNum() *TimedQuota {
	if x != nil {
		return x.WriteNum
	}
	return nil
}

func (x *Throttle) GetWriteSize() *TimedQuota {
	if x != nil {
		return x.WriteSize
	}
	return nil
}

func (x *Throttle) GetReadNum() *TimedQuota {
	if x != nil {
		return x.ReadNum
	}
	return nil
}

func (x *Throttle) GetReadSize() *TimedQuota {
	if x != nil {
		return x.ReadSize
	}
	return nil
}

func (x *Throttle) GetReqCapacityUnit() *TimedQuota {
	if x != nil {
		return x.ReqCapacityUnit
	}
	return nil
}

func (x *Throttle) GetWriteCapacityUnit() *TimedQuota {
	if x != nil {
		return x.WriteCapacityUnit
	}
	return nil
}

func (x *Throttle) GetReadCapacityUnit() *TimedQuota {
	if x != nil {
		return x.ReadCapacityUnit
	}
	return nil
}

type ThrottleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       *ThrottleType `protobuf:"varint,1,opt,name=type,enum=hbase.pb.ThrottleType" json:"type,omitempty"`
	TimedQuota *TimedQuota   `protobuf:"bytes,2,opt,name=timed_quota,json=timedQuota" json:"timed_quota,omitempty"`
}

func (x *ThrottleRequest) Reset() {
	*x = ThrottleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThrottleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrottleRequest) ProtoMessage() {}

func (x *ThrottleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrottleRequest.ProtoReflect.Descriptor instead.
func (*ThrottleRequest) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{2}
}

func (x *ThrottleRequest) GetType() ThrottleType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ThrottleType_REQUEST_NUMBER
}

func (x *ThrottleRequest) GetTimedQuota() *TimedQuota {
	if x != nil {
		return x.TimedQuota
	}
	return nil
}

type Quotas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BypassGlobals *bool       `protobuf:"varint,1,opt,name=bypass_globals,json=bypassGlobals,def=0" json:"bypass_globals,omitempty"`
	Throttle      *Throttle   `protobuf:"bytes,2,opt,name=throttle" json:"throttle,omitempty"`
	Space         *SpaceQuota `protobuf:"bytes,3,opt,name=space" json:"space,omitempty"`
}

// Default values for Quotas fields.
const (
	Default_Quotas_BypassGlobals = bool(false)
)

func (x *Quotas) Reset() {
	*x = Quotas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quotas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quotas) ProtoMessage() {}

func (x *Quotas) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quotas.ProtoReflect.Descriptor instead.
func (*Quotas) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{3}
}

func (x *Quotas) GetBypassGlobals() bool {
	if x != nil && x.BypassGlobals != nil {
		return *x.BypassGlobals
	}
	return Default_Quotas_BypassGlobals
}

func (x *Quotas) GetThrottle() *Throttle {
	if x != nil {
		return x.Throttle
	}
	return nil
}

func (x *Quotas) GetSpace() *SpaceQuota {
	if x != nil {
		return x.Space
	}
	return nil
}

type QuotaUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuotaUsage) Reset() {
	*x = QuotaUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuotaUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaUsage) ProtoMessage() {}

func (x *QuotaUsage) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaUsage.ProtoReflect.Descriptor instead.
func (*QuotaUsage) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{4}
}

// Defines a limit on the amount of filesystem space used by a table/namespace
type SpaceQuota struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SoftLimit       *uint64               `protobuf:"varint,1,opt,name=soft_limit,json=softLimit" json:"soft_limit,omitempty"`                                                      // The limit of bytes for this quota
	ViolationPolicy *SpaceViolationPolicy `protobuf:"varint,2,opt,name=violation_policy,json=violationPolicy,enum=hbase.pb.SpaceViolationPolicy" json:"violation_policy,omitempty"` // The action to take when the quota is violated
	Remove          *bool                 `protobuf:"varint,3,opt,name=remove,def=0" json:"remove,omitempty"`                                                                       // When true, remove the quota.
}

// Default values for SpaceQuota fields.
const (
	Default_SpaceQuota_Remove = bool(false)
)

func (x *SpaceQuota) Reset() {
	*x = SpaceQuota{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceQuota) ProtoMessage() {}

func (x *SpaceQuota) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceQuota.ProtoReflect.Descriptor instead.
func (*SpaceQuota) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{5}
}

func (x *SpaceQuota) GetSoftLimit() uint64 {
	if x != nil && x.SoftLimit != nil {
		return *x.SoftLimit
	}
	return 0
}

func (x *SpaceQuota) GetViolationPolicy() SpaceViolationPolicy {
	if x != nil && x.ViolationPolicy != nil {
		return *x.ViolationPolicy
	}
	return SpaceViolationPolicy_DISABLE
}

func (x *SpaceQuota) GetRemove() bool {
	if x != nil && x.Remove != nil {
		return *x.Remove
	}
	return Default_SpaceQuota_Remove
}

// The Request to limit space usage (to allow for schema evolution not tied to SpaceQuota).
type SpaceLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quota *SpaceQuota `protobuf:"bytes,1,opt,name=quota" json:"quota,omitempty"`
}

func (x *SpaceLimitRequest) Reset() {
	*x = SpaceLimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceLimitRequest) ProtoMessage() {}

func (x *SpaceLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceLimitRequest.ProtoReflect.Descriptor instead.
func (*SpaceLimitRequest) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{6}
}

func (x *SpaceLimitRequest) GetQuota() *SpaceQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

// Represents the state of a quota on a table. Either the quota is not in violation
// or it is in violation there is a violation policy which should be in effect.
type SpaceQuotaStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ViolationPolicy *SpaceViolationPolicy `protobuf:"varint,1,opt,name=violation_policy,json=violationPolicy,enum=hbase.pb.SpaceViolationPolicy" json:"violation_policy,omitempty"`
	InViolation     *bool                 `protobuf:"varint,2,opt,name=in_violation,json=inViolation" json:"in_violation,omitempty"`
}

func (x *SpaceQuotaStatus) Reset() {
	*x = SpaceQuotaStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceQuotaStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceQuotaStatus) ProtoMessage() {}

func (x *SpaceQuotaStatus) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceQuotaStatus.ProtoReflect.Descriptor instead.
func (*SpaceQuotaStatus) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{7}
}

func (x *SpaceQuotaStatus) GetViolationPolicy() SpaceViolationPolicy {
	if x != nil && x.ViolationPolicy != nil {
		return *x.ViolationPolicy
	}
	return SpaceViolationPolicy_DISABLE
}

func (x *SpaceQuotaStatus) GetInViolation() bool {
	if x != nil && x.InViolation != nil {
		return *x.InViolation
	}
	return false
}

// Message stored in the value of hbase:quota table to denote the status of a table WRT
// the quota applicable to it.
type SpaceQuotaSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuotaStatus *SpaceQuotaStatus `protobuf:"bytes,1,opt,name=quota_status,json=quotaStatus" json:"quota_status,omitempty"`
	QuotaUsage  *uint64           `protobuf:"varint,2,opt,name=quota_usage,json=quotaUsage" json:"quota_usage,omitempty"`
	QuotaLimit  *uint64           `protobuf:"varint,3,opt,name=quota_limit,json=quotaLimit" json:"quota_limit,omitempty"`
}

func (x *SpaceQuotaSnapshot) Reset() {
	*x = SpaceQuotaSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceQuotaSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceQuotaSnapshot) ProtoMessage() {}

func (x *SpaceQuotaSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceQuotaSnapshot.ProtoReflect.Descriptor instead.
func (*SpaceQuotaSnapshot) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{8}
}

func (x *SpaceQuotaSnapshot) GetQuotaStatus() *SpaceQuotaStatus {
	if x != nil {
		return x.QuotaStatus
	}
	return nil
}

func (x *SpaceQuotaSnapshot) GetQuotaUsage() uint64 {
	if x != nil && x.QuotaUsage != nil {
		return *x.QuotaUsage
	}
	return 0
}

func (x *SpaceQuotaSnapshot) GetQuotaLimit() uint64 {
	if x != nil && x.QuotaLimit != nil {
		return *x.QuotaLimit
	}
	return 0
}

type GetSpaceQuotaRegionSizesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSpaceQuotaRegionSizesRequest) Reset() {
	*x = GetSpaceQuotaRegionSizesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceQuotaRegionSizesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceQuotaRegionSizesRequest) ProtoMessage() {}

func (x *GetSpaceQuotaRegionSizesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceQuotaRegionSizesRequest.ProtoReflect.Descriptor instead.
func (*GetSpaceQuotaRegionSizesRequest) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{9}
}

type GetSpaceQuotaRegionSizesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sizes []*GetSpaceQuotaRegionSizesResponse_RegionSizes `protobuf:"bytes,1,rep,name=sizes" json:"sizes,omitempty"`
}

func (x *GetSpaceQuotaRegionSizesResponse) Reset() {
	*x = GetSpaceQuotaRegionSizesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceQuotaRegionSizesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceQuotaRegionSizesResponse) ProtoMessage() {}

func (x *GetSpaceQuotaRegionSizesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceQuotaRegionSizesResponse.ProtoReflect.Descriptor instead.
func (*GetSpaceQuotaRegionSizesResponse) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{10}
}

func (x *GetSpaceQuotaRegionSizesResponse) GetSizes() []*GetSpaceQuotaRegionSizesResponse_RegionSizes {
	if x != nil {
		return x.Sizes
	}
	return nil
}

type GetSpaceQuotaSnapshotsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSpaceQuotaSnapshotsRequest) Reset() {
	*x = GetSpaceQuotaSnapshotsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceQuotaSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceQuotaSnapshotsRequest) ProtoMessage() {}

func (x *GetSpaceQuotaSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceQuotaSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*GetSpaceQuotaSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{11}
}

type GetSpaceQuotaSnapshotsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Snapshots []*GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot `protobuf:"bytes,1,rep,name=snapshots" json:"snapshots,omitempty"`
}

func (x *GetSpaceQuotaSnapshotsResponse) Reset() {
	*x = GetSpaceQuotaSnapshotsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceQuotaSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceQuotaSnapshotsResponse) ProtoMessage() {}

func (x *GetSpaceQuotaSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceQuotaSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*GetSpaceQuotaSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{12}
}

func (x *GetSpaceQuotaSnapshotsResponse) GetSnapshots() []*GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type GetQuotaStatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQuotaStatesRequest) Reset() {
	*x = GetQuotaStatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotaStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaStatesRequest) ProtoMessage() {}

func (x *GetQuotaStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaStatesRequest.ProtoReflect.Descriptor instead.
func (*GetQuotaStatesRequest) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{13}
}

type GetQuotaStatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableSnapshots []*GetQuotaStatesResponse_TableQuotaSnapshot     `protobuf:"bytes,1,rep,name=table_snapshots,json=tableSnapshots" json:"table_snapshots,omitempty"`
	NsSnapshots    []*GetQuotaStatesResponse_NamespaceQuotaSnapshot `protobuf:"bytes,2,rep,name=ns_snapshots,json=nsSnapshots" json:"ns_snapshots,omitempty"`
}

func (x *GetQuotaStatesResponse) Reset() {
	*x = GetQuotaStatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotaStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaStatesResponse) ProtoMessage() {}

func (x *GetQuotaStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaStatesResponse.ProtoReflect.Descriptor instead.
func (*GetQuotaStatesResponse) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{14}
}

func (x *GetQuotaStatesResponse) GetTableSnapshots() []*GetQuotaStatesResponse_TableQuotaSnapshot {
	if x != nil {
		return x.TableSnapshots
	}
	return nil
}

func (x *GetQuotaStatesResponse) GetNsSnapshots() []*GetQuotaStatesResponse_NamespaceQuotaSnapshot {
	if x != nil {
		return x.NsSnapshots
	}
	return nil
}

type GetSpaceQuotaRegionSizesResponse_RegionSizes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName *TableName `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Size      *uint64    `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (x *GetSpaceQuotaRegionSizesResponse_RegionSizes) Reset() {
	*x = GetSpaceQuotaRegionSizesResponse_RegionSizes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceQuotaRegionSizesResponse_RegionSizes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceQuotaRegionSizesResponse_RegionSizes) ProtoMessage() {}

func (x *GetSpaceQuotaRegionSizesResponse_RegionSizes) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceQuotaRegionSizesResponse_RegionSizes.ProtoReflect.Descriptor instead.
func (*GetSpaceQuotaRegionSizesResponse_RegionSizes) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{10, 0}
}

func (x *GetSpaceQuotaRegionSizesResponse_RegionSizes) GetTableName() *TableName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *GetSpaceQuotaRegionSizesResponse_RegionSizes) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

// Cannot use TableName as a map key, do the repeated nested message by hand.
type GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName *TableName          `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Snapshot  *SpaceQuotaSnapshot `protobuf:"bytes,2,opt,name=snapshot" json:"snapshot,omitempty"`
}

func (x *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) Reset() {
	*x = GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) ProtoMessage() {}

func (x *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot.ProtoReflect.Descriptor instead.
func (*GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{12, 0}
}

func (x *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) GetTableName() *TableName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) GetSnapshot() *SpaceQuotaSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type GetQuotaStatesResponse_TableQuotaSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName *TableName          `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Snapshot  *SpaceQuotaSnapshot `protobuf:"bytes,2,opt,name=snapshot" json:"snapshot,omitempty"`
}

func (x *GetQuotaStatesResponse_TableQuotaSnapshot) Reset() {
	*x = GetQuotaStatesResponse_TableQuotaSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotaStatesResponse_TableQuotaSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaStatesResponse_TableQuotaSnapshot) ProtoMessage() {}

func (x *GetQuotaStatesResponse_TableQuotaSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaStatesResponse_TableQuotaSnapshot.ProtoReflect.Descriptor instead.
func (*GetQuotaStatesResponse_TableQuotaSnapshot) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{14, 0}
}

func (x *GetQuotaStatesResponse_TableQuotaSnapshot) GetTableName() *TableName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *GetQuotaStatesResponse_TableQuotaSnapshot) GetSnapshot() *SpaceQuotaSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type GetQuotaStatesResponse_NamespaceQuotaSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace *string             `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Snapshot  *SpaceQuotaSnapshot `protobuf:"bytes,2,opt,name=snapshot" json:"snapshot,omitempty"`
}

func (x *GetQuotaStatesResponse_NamespaceQuotaSnapshot) Reset() {
	*x = GetQuotaStatesResponse_NamespaceQuotaSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Quota_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotaStatesResponse_NamespaceQuotaSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaStatesResponse_NamespaceQuotaSnapshot) ProtoMessage() {}

func (x *GetQuotaStatesResponse_NamespaceQuotaSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_Quota_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaStatesResponse_NamespaceQuotaSnapshot.ProtoReflect.Descriptor instead.
func (*GetQuotaStatesResponse_NamespaceQuotaSnapshot) Descriptor() ([]byte, []int) {
	return file_Quota_proto_rawDescGZIP(), []int{14, 1}
}

func (x *GetQuotaStatesResponse_NamespaceQuotaSnapshot) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *GetQuotaStatesResponse_NamespaceQuotaSnapshot) GetSnapshot() *SpaceQuotaSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

var File_Quota_proto protoreflect.FileDescriptor

var file_Quota_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x68,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x1a, 0x0b, 0x48, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x01, 0x0a, 0x0a, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x51, 0x75,
	0x6f, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x74,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65,
	0x55, 0x6e, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x66, 0x74, 0x5f, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x6f, 0x66, 0x74, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x3a, 0x07,
	0x4d, 0x41, 0x43, 0x48, 0x49, 0x4e, 0x45, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x22, 0x82,
	0x04, 0x0a, 0x08, 0x54, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x72,
	0x65, 0x71, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x52, 0x06, 0x72, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x12, 0x2f, 0x0a, 0x08, 0x72, 0x65,
	0x71, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x52, 0x07, 0x72, 0x65, 0x71, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x52, 0x08, 0x77, 0x72, 0x69, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x33,
	0x0a, 0x0a, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x64, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x09, 0x77, 0x72, 0x69, 0x74, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x07, 0x72, 0x65, 0x61,
	0x64, 0x4e, 0x75, 0x6d, 0x12, 0x31, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x08, 0x72,
	0x65, 0x61, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x40, 0x0a, 0x11, 0x72, 0x65, 0x71, 0x5f, 0x63,
	0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x64, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x0f, 0x72, 0x65, 0x71, 0x43, 0x61, 0x70,
	0x61, 0x63, 0x69, 0x74, 0x79, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x44, 0x0a, 0x13, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x75, 0x6e, 0x69, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x11, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x55, 0x6e, 0x69, 0x74, 0x12,
	0x42, 0x0a, 0x12, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x52, 0x10, 0x72, 0x65, 0x61, 0x64, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x55,
	0x6e, 0x69, 0x74, 0x22, 0x74, 0x0a, 0x0f, 0x54, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e,
	0x54, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x64, 0x5f, 0x71, 0x75, 0x6f, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x0a, 0x74,
	0x69, 0x6d, 0x65, 0x64, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x22, 0x92, 0x01, 0x0a, 0x06, 0x51, 0x75,
	0x6f, 0x74, 0x61, 0x73, 0x12, 0x2c, 0x0a, 0x0e, 0x62, 0x79, 0x70, 0x61, 0x73, 0x73, 0x5f, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x05, 0x66, 0x61,
	0x6c, 0x73, 0x65, 0x52, 0x0d, 0x62, 0x79, 0x70, 0x61, 0x73, 0x73, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x73, 0x12, 0x2e, 0x0a, 0x08, 0x74, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e,
	0x54, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x08, 0x74, 0x68, 0x72, 0x6f, 0x74, 0x74,
	0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x0c,
	0x0a, 0x0a, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x55, 0x73, 0x61, 0x67, 0x65, 0x22, 0x95, 0x01, 0x0a,
	0x0a, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x6f, 0x66, 0x74, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x73, 0x6f, 0x66, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x49, 0x0a, 0x10, 0x76, 0x69,
	0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x52, 0x0f, 0x76, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x1d, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x52, 0x06, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x22, 0x3f, 0x0a, 0x11, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x71, 0x75, 0x6f,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x05,
	0x71, 0x75, 0x6f, 0x74, 0x61, 0x22, 0x80, 0x01, 0x0a, 0x10, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x49, 0x0a, 0x10, 0x76, 0x69,
	0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x52, 0x0f, 0x76, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x5f, 0x76, 0x69, 0x6f, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x6e, 0x56,
	0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x95, 0x01, 0x0a, 0x12, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12,
	0x3d, 0x0a, 0x0c, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0x21, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0xc7, 0x01, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x05, 0x73, 0x69, 0x7a, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x52,
	0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x1a, 0x55, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x53, 0x69, 0x7a, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x09,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x1f, 0x0a,
	0x1d, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x80,
	0x02, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x59, 0x0a, 0x09, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x52, 0x09, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x1a, 0x82, 0x01, 0x0a,
	0x12, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x68, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xc9, 0x03, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33,
	0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x52, 0x0e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x73, 0x12, 0x5a, 0x0a, 0x0c, 0x6e, 0x73, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x68, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x52, 0x0b, 0x6e, 0x73, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x1a,
	0x82, 0x01, 0x0a, 0x12, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x73, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x68,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x1a, 0x70, 0x0a, 0x16, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x08,
	0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x08, 0x73, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2a, 0x26, 0x0a, 0x0a, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x53,
	0x63, 0x6f, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x41, 0x43, 0x48, 0x49, 0x4e, 0x45, 0x10, 0x02, 0x2a, 0xc2,
	0x01, 0x0a, 0x0c, 0x54, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x0e, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x55, 0x4d, 0x42, 0x45,
	0x52, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x53,
	0x49, 0x5a, 0x45, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f, 0x4e,
	0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x52, 0x49, 0x54, 0x45,
	0x5f, 0x53, 0x49, 0x5a, 0x45, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x45, 0x41, 0x44, 0x5f,
	0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x41, 0x44,
	0x5f, 0x53, 0x49, 0x5a, 0x45, 0x10, 0x06, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x45, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x5f, 0x43, 0x41, 0x50, 0x41, 0x43, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x49, 0x54,
	0x10, 0x07, 0x12, 0x17, 0x0a, 0x13, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f, 0x43, 0x41, 0x50, 0x41,
	0x43, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x49, 0x54, 0x10, 0x08, 0x12, 0x16, 0x0a, 0x12, 0x52,
	0x45, 0x41, 0x44, 0x5f, 0x43, 0x41, 0x50, 0x41, 0x43, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x49,
	0x54, 0x10, 0x09, 0x2a, 0x24, 0x0a, 0x09, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0c, 0x0a, 0x08, 0x54, 0x48, 0x52, 0x4f, 0x54, 0x54, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x53, 0x50, 0x41, 0x43, 0x45, 0x10, 0x02, 0x2a, 0x5d, 0x0a, 0x14, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x19,
	0x0a, 0x15, 0x4e, 0x4f, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50,
	0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x5f,
	0x57, 0x52, 0x49, 0x54, 0x45, 0x53, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x5f, 0x49,
	0x4e, 0x53, 0x45, 0x52, 0x54, 0x53, 0x10, 0x04, 0x42, 0x4f, 0x0a, 0x31, 0x6f, 0x72, 0x67, 0x2e,
	0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x0b, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x48, 0x01, 0x5a, 0x05, 0x2e, 0x2e,
	0x2f, 0x70, 0x62, 0x88, 0x01, 0x01, 0xa0, 0x01, 0x01,
}

var (
	file_Quota_proto_rawDescOnce sync.Once
	file_Quota_proto_rawDescData = file_Quota_proto_rawDesc
)

func file_Quota_proto_rawDescGZIP() []byte {
	file_Quota_proto_rawDescOnce.Do(func() {
		file_Quota_proto_rawDescData = protoimpl.X.CompressGZIP(file_Quota_proto_rawDescData)
	})
	return file_Quota_proto_rawDescData
}

var file_Quota_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_Quota_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_Quota_proto_goTypes = []interface{}{
	(QuotaScope)(0),                                           // 0: hbase.pb.QuotaScope
	(ThrottleType)(0),                                         // 1: hbase.pb.ThrottleType
	(QuotaType)(0),                                            // 2: hbase.pb.QuotaType
	(SpaceViolationPolicy)(0),                                 // 3: hbase.pb.SpaceViolationPolicy
	(*TimedQuota)(nil),                                        // 4: hbase.pb.TimedQuota
	(*Throttle)(nil),                                          // 5: hbase.pb.Throttle
	(*ThrottleRequest)(nil),                                   // 6: hbase.pb.ThrottleRequest
	(*Quotas)(nil),                                            // 7: hbase.pb.Quotas
	(*QuotaUsage)(nil),                                        // 8: hbase.pb.QuotaUsage
	(*SpaceQuota)(nil),                                        // 9: hbase.pb.SpaceQuota
	(*SpaceLimitRequest)(nil),                                 // 10: hbase.pb.SpaceLimitRequest
	(*SpaceQuotaStatus)(nil),                                  // 11: hbase.pb.SpaceQuotaStatus
	(*SpaceQuotaSnapshot)(nil),                                // 12: hbase.pb.SpaceQuotaSnapshot
	(*GetSpaceQuotaRegionSizesRequest)(nil),                   // 13: hbase.pb.GetSpaceQuotaRegionSizesRequest
	(*GetSpaceQuotaRegionSizesResponse)(nil),                  // 14: hbase.pb.GetSpaceQuotaRegionSizesResponse
	(*GetSpaceQuotaSnapshotsRequest)(nil),                     // 15: hbase.pb.GetSpaceQuotaSnapshotsRequest
	(*GetSpaceQuotaSnapshotsResponse)(nil),                    // 16: hbase.pb.GetSpaceQuotaSnapshotsResponse
	(*GetQuotaStatesRequest)(nil),                             // 17: hbase.pb.GetQuotaStatesRequest
	(*GetQuotaStatesResponse)(nil),                            // 18: hbase.pb.GetQuotaStatesResponse
	(*GetSpaceQuotaRegionSizesResponse_RegionSizes)(nil),      // 19: hbase.pb.GetSpaceQuotaRegionSizesResponse.RegionSizes
	(*GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot)(nil), // 20: hbase.pb.GetSpaceQuotaSnapshotsResponse.TableQuotaSnapshot
	(*GetQuotaStatesResponse_TableQuotaSnapshot)(nil),         // 21: hbase.pb.GetQuotaStatesResponse.TableQuotaSnapshot
	(*GetQuotaStatesResponse_NamespaceQuotaSnapshot)(nil),     // 22: hbase.pb.GetQuotaStatesResponse.NamespaceQuotaSnapshot
	(TimeUnit)(0),                                             // 23: hbase.pb.TimeUnit
	(*TableName)(nil),                                         // 24: hbase.pb.TableName
}
var file_Quota_proto_depIdxs = []int32{
	23, // 0: hbase.pb.TimedQuota.time_unit:type_name -> hbase.pb.TimeUnit
	0,  // 1: hbase.pb.TimedQuota.scope:type_name -> hbase.pb.QuotaScope
	4,  // 2: hbase.pb.Throttle.req_num:type_name -> hbase.pb.TimedQuota
	4,  // 3: hbase.pb.Throttle.req_size:type_name -> hbase.pb.TimedQuota
	4,  // 4: hbase.pb.Throttle.write_num:type_name -> hbase.pb.TimedQuota
	4,  // 5: hbase.pb.Throttle.write_size:type_name -> hbase.pb.TimedQuota
	4,  // 6: hbase.pb.Throttle.read_num:type_name -> hbase.pb.TimedQuota
	4,  // 7: hbase.pb.Throttle.read_size:type_name -> hbase.pb.TimedQuota
	4,  // 8: hbase.pb.Throttle.req_capacity_unit:type_name -> hbase.pb.TimedQuota
	4,  // 9: hbase.pb.Throttle.write_capacity_unit:type_name -> hbase.pb.TimedQuota
	4,  // 10: hbase.pb.Throttle.read_capacity_unit:type_name -> hbase.pb.TimedQuota
	1,  // 11: hbase.pb.ThrottleRequest.type:type_name -> hbase.pb.ThrottleType
	4,  // 12: hbase.pb.ThrottleRequest.timed_quota:type_name -> hbase.pb.TimedQuota
	5,  // 13: hbase.pb.Quotas.throttle:type_name -> hbase.pb.Throttle
	9,  // 14: hbase.pb.Quotas.space:type_name -> hbase.pb.SpaceQuota
	3,  // 15: hbase.pb.SpaceQuota.violation_policy:type_name -> hbase.pb.SpaceViolationPolicy
	9,  // 16: hbase.pb.SpaceLimitRequest.quota:type_name -> hbase.pb.SpaceQuota
	3,  // 17: hbase.pb.SpaceQuotaStatus.violation_policy:type_name -> hbase.pb.SpaceViolationPolicy
	11, // 18: hbase.pb.SpaceQuotaSnapshot.quota_status:type_name -> hbase.pb.SpaceQuotaStatus
	19, // 19: hbase.pb.GetSpaceQuotaRegionSizesResponse.sizes:type_name -> hbase.pb.GetSpaceQuotaRegionSizesResponse.RegionSizes
	20, // 20: hbase.pb.GetSpaceQuotaSnapshotsResponse.snapshots:type_name -> hbase.pb.GetSpaceQuotaSnapshotsResponse.TableQuotaSnapshot
	21, // 21: hbase.pb.GetQuotaStatesResponse.table_snapshots:type_name -> hbase.pb.GetQuotaStatesResponse.TableQuotaSnapshot
	22, // 22: hbase.pb.GetQuotaStatesResponse.ns_snapshots:type_name -> hbase.pb.GetQuotaStatesResponse.NamespaceQuotaSnapshot
	24, // 23: hbase.pb.GetSpaceQuotaRegionSizesResponse.RegionSizes.table_name:type_name -> hbase.pb.TableName
	24, // 24: hbase.pb.GetSpaceQuotaSnapshotsResponse.TableQuotaSnapshot.table_name:type_name -> hbase.pb.TableName
	12, // 25: hbase.pb.GetSpaceQuotaSnapshotsResponse.TableQuotaSnapshot.snapshot:type_name -> hbase.pb.SpaceQuotaSnapshot
	24, // 26: hbase.pb.GetQuotaStatesResponse.TableQuotaSnapshot.table_name:type_name -> hbase.pb.TableName
	12, // 27: hbase.pb.GetQuotaStatesResponse.TableQuotaSnapshot.snapshot:type_name -> hbase.pb.SpaceQuotaSnapshot
	12, // 28: hbase.pb.GetQuotaStatesResponse.NamespaceQuotaSnapshot.snapshot:type_name -> hbase.pb.SpaceQuotaSnapshot
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_Quota_proto_init() }
func file_Quota_proto_init() {
	if File_Quota_proto != nil {
		return
	}
	file_HBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Quota_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimedQuota); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Throttle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThrottleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quotas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuotaUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceQuota); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceLimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceQuotaStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceQuotaSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceQuotaRegionSizesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceQuotaRegionSizesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceQuotaSnapshotsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceQuotaSnapshotsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotaStatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotaStatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceQuotaRegionSizesResponse_RegionSizes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotaStatesResponse_TableQuotaSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Quota_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotaStatesResponse_NamespaceQuotaSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Quota_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Quota_proto_goTypes,
		DependencyIndexes: file_Quota_proto_depIdxs,
		EnumInfos:         file_Quota_proto_enumTypes,
		MessageInfos:      file_Quota_proto_msgTypes,
	}.Build()
	File_Quota_proto = out.File
	file_Quota_proto_rawDesc = nil
	file_Quota_proto_goTypes = nil
	file_Quota_proto_depIdxs = nil
}
