//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-rc.1
// 	protoc        v3.17.3
// source: TestProcedure.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestTableDDLStateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName *string `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
}

func (x *TestTableDDLStateData) Reset() {
	*x = TestTableDDLStateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TestProcedure_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestTableDDLStateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTableDDLStateData) ProtoMessage() {}

func (x *TestTableDDLStateData) ProtoReflect() protoreflect.Message {
	mi := &file_TestProcedure_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTableDDLStateData.ProtoReflect.Descriptor instead.
func (*TestTableDDLStateData) Descriptor() ([]byte, []int) {
	return file_TestProcedure_proto_rawDescGZIP(), []int{0}
}

func (x *TestTableDDLStateData) GetTableName() string {
	if x != nil && x.TableName != nil {
		return *x.TableName
	}
	return ""
}

var File_TestProcedure_proto protoreflect.FileDescriptor

var file_TestProcedure_proto_rawDesc = []byte{
	0x0a, 0x13, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x15, 0x54, 0x65, 0x73, 0x74, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x44, 0x44, 0x4c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x56, 0x0a,
	0x35, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f,
	0x6f, 0x70, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x65, 0x64, 0x2e,
	0x69, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x13, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x64, 0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x05, 0x2e, 0x2e, 0x2f,
	0x70, 0x62, 0x88, 0x01, 0x01,
}

var (
	file_TestProcedure_proto_rawDescOnce sync.Once
	file_TestProcedure_proto_rawDescData = file_TestProcedure_proto_rawDesc
)

func file_TestProcedure_proto_rawDescGZIP() []byte {
	file_TestProcedure_proto_rawDescOnce.Do(func() {
		file_TestProcedure_proto_rawDescData = protoimpl.X.CompressGZIP(file_TestProcedure_proto_rawDescData)
	})
	return file_TestProcedure_proto_rawDescData
}

var file_TestProcedure_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TestProcedure_proto_goTypes = []interface{}{
	(*TestTableDDLStateData)(nil), // 0: TestTableDDLStateData
}
var file_TestProcedure_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TestProcedure_proto_init() }
func file_TestProcedure_proto_init() {
	if File_TestProcedure_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TestProcedure_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestTableDDLStateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TestProcedure_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TestProcedure_proto_goTypes,
		DependencyIndexes: file_TestProcedure_proto_depIdxs,
		MessageInfos:      file_TestProcedure_proto_msgTypes,
	}.Build()
	File_TestProcedure_proto = out.File
	file_TestProcedure_proto_rawDesc = nil
	file_TestProcedure_proto_goTypes = nil
	file_TestProcedure_proto_depIdxs = nil
}
